# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[(b'F', b'Funcionario'), (b'U', b'Usuario')], default='U', max_length=1),
            preserve_default=False,
        ),
    ]
