# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-06 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='audio',
            new_name='audioDownload',
        ),
        migrations.AddField(
            model_name='audio',
            name='audioPlay',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
    ]
