# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-09 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='This is a generic description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='relatedCategories',
            field=models.ManyToManyField(related_name='_category_relatedCategories_+', to='sonidosLibresApp.Category'),
        ),
    ]
