# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0002_usuario_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipobicicleta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[('F', 'Funcionario'), ('U', 'Usuario')], max_length=1),
        ),
    ]
