# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0002_auto_20161008_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.URLField(default='https://github.com/slinan/sonidosLibresG2/blob/master/docs/assets/img/albums/1.jpg?raw=true'),
            preserve_default=False,
        ),
    ]
