# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0004_auto_20161012_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='albums', to='sonidosLibresApp.Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='albums', to='sonidosLibresApp.Category'),
        ),
    ]
