# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0004_auto_20160831_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='puntoPrestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.PuntoPrestamo'),
        ),
    ]
