# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0007_auto_20160924_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='puntoPrestamo',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='tipoDeInfraccion',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='audio',
            name='downloadsCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='numOfRatings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='playCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='uploadDate',
            field=models.DateField(default=datetime.datetime(2016, 9, 24, 16, 41, 5, 82327, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='categories',
            field=models.ManyToManyField(related_name='audios', to='sonidosLibresApp.Category'),
        ),
        migrations.DeleteModel(
            name='Bicicleta',
        ),
        migrations.DeleteModel(
            name='Multa',
        ),
        migrations.DeleteModel(
            name='PuntoPrestamo',
        ),
        migrations.DeleteModel(
            name='TipoBicicleta',
        ),
        migrations.DeleteModel(
            name='TipoInfraccion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='commentary',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Audio'),
        ),
    ]
