# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0008_auto_20160924_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('numOfRatings', models.IntegerField()),
                ('categories', models.ManyToManyField(related_name='albums', to='sonidosLibresApp.Category')),
            ],
        ),
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name_plural': 'commentaries'},
        ),
        migrations.AddField(
            model_name='audio',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Album'),
        ),
    ]
