# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-27 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0009_auto_20160924_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='album',
        ),
        migrations.AddField(
            model_name='audio',
            name='album',
            field=models.ManyToManyField(related_name='audios', to='sonidosLibresApp.Album'),
        ),
    ]
