# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sonidosLibresApp', '0010_auto_20160926_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.URLField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'artists',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='sonidosLibresApp.Artist'),
        ),
        migrations.AddField(
            model_name='audio',
            name='artists',
            field=models.ManyToManyField(related_name='audios', to='sonidosLibresApp.Artist'),
        ),
    ]
