# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-03 00:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sonidosLibresApp', '0011_auto_20161001_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='audio',
            name='rating',
            field=models.FloatField(),
        ),
    ]
